development:
  adapter: postgresql
  encoding: unicode
  database: C330507_gingerboy_dev
  pool: 5
  min_messages: WARNING
  host: pgsql1101.ixwebhosting.com
  port: 5432
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: C330507_gingerboy_test
  pool: 5
  min_messages: WARNING
  host: pgsql1101.ixwebhosting.com
  port: 5432
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>



production:
  adapter: postgresql
  host: pgsql1101.ixwebhosting.com
  port: 5432
  encoding: unicode
  database: C330507_gingerboy_prod
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
