development:
  adapter: postgresql
  encoding: unicode
  database: GingerBoyDev_development
  pool: 5
  min_messages: WARNING
  host: localhost
  port: 5432
  username: gingerboy

test:
  adapter: postgresql
  encoding: unicode
  database: GingerBoyDev_test
  pool: 5
  min_messages: WARNING
  host: localhost
  port: 5432
  username: gingerboy


production:
  adapter: postgresql
  encoding: unicode
  database: GingerBoyDev_production
  pool: 5
  username: gingerboy
  password:
