development:
  adapter: mysql2
  encoding: utf8
  database: GingerBoyDev_development
  pool: 5
  username: <%= Figaro.env.db_username %>
  password: <%= Figaro.env.db_password %>

test:
  adapter: mysql2
  encoding: utf8
  database: GingerBoyDev_test
  pool: 5
  username: <%= Figaro.env.db_username %>
  password: <%= Figaro.env.db_password %>

production:
  adapter: mysql2
  encoding: utf8
  database: GingerBoyDev_production
  pool: 5
  username: <%= Figaro.env.db_username %>
  password: <%= Figaro.env.db_password %>
