development:
  adapter: postgresql
  encoding: unicode
  database: C330507_gingerboy_dev
  pool: 5
  min_messages: WARNING
  host: localhost
  port: 5432
  username: gingerboy

test:
  adapter: postgresql
  encoding: unicode
  database: C330507_gingerboy_test
  pool: 5
  min_messages: WARNING
  host: localhost
  port: 5432
  username: gingerboy



production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: C330507_gingerboy_prod
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
